Remove translator deprecations
sonata-project/SonataNewsBundle pull request #650
Opened 2020-10-04 19:25 UTC by core23

## Subject

I am targeting this branch, because this is BC.

## Changelog

```markdown
### Removed
- Remove translator deprecations
```

2020-10-04 19:30 UTC, VincentLanglet requested changes
This is BC-break. 

https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Translation/TranslatorInterface.php#L24

The old Interface doesn't implement the new one. So if someone pass the old implements as argument, it won't work anymore.

2020-10-04 19:47 UTC, core23 commented
Oh you're right. I will update this PR to support both interfaces

2020-10-04 20:43 UTC, VincentLanglet commented on src/Action/AbstractPostArchiveAction.php
> +            throw new \TypeError(sprintf('Argument 3 passed to %s() must be an instance of %s, %s given.', __METHOD__, TranslatorInterface::class, \is_object($translator) ? \get_class($translator) :
```suggestion
            throw new \TypeError(sprintf('Argument 3 passed to %s() must be an instance of %s, %s given.', __METHOD__, TranslatorInterface::class, \get_class($translator)));
```

2020-10-07 17:04 UTC, VincentLanglet approved these changes

2020-10-08 06:50 UTC, franmomu approved these changes

2020-10-08 07:08 UTC, merged

2020-10-08 07:08 UTC, VincentLanglet commented
@core23 Thanks

2020-11-02 08:01 UTC, OskarStark commented
Are you fine with `minor` label?