Remove deprecated ReST API with dependencies
sonata-project/SonataNewsBundle pull request #780
Opened 2021-09-23 12:55 UTC by wbloszyk

## Subject

Remove ReST API with dependencies and update routing with tests.

I am targeting this branch, because this should be done in unstable branch.

2021-09-23 13:06 UTC, VincentLanglet reviewed
You should try to remove datagrid bundle too.

2021-09-23 13:12 UTC, wbloszyk commented
> You should try to remove datagrid bundle too.

I think about it too. In NewsBundle we use pagination in frontend. We can remove datagrid bundle in favor of KnpPaginationBundle. I will wait with it for now.

2021-09-23 13:23 UTC, VincentLanglet commented
> > You should try to remove datagrid bundle too.
> 
> I think about it too. In NewsBundle we use pagination in frontend. We can remove datagrid bundle in favor of KnpPaginationBundle. I will wait with it for now.

The DatagridBundle pagination was supposed to be only used for API.

For frontend, there is already a Pager/Datagrid class in the AdminBundle (and his persistence bundle), made for this.

2021-09-25 10:52 UTC, wbloszyk commented
Ready to review. 
PHPStan and Psalm will added after merge #779 to 3.x and merge it to 4.x.

2021-09-25 14:02 UTC, core23 requested changes

2021-09-25 14:02 UTC, core23 commented on src/Action/ViewPostAction.php
> +        dump($permalink);
Debug code

2021-09-25 14:03 UTC, core23 requested changes

2021-09-25 14:03 UTC, core23 commented on src/Pagination/BasePaginator.php
> +     * @var
Type is missing

2021-09-25 14:08 UTC, VincentLanglet approved these changes

2021-09-25 14:20 UTC, core23 approved these changes

2021-09-25 14:22 UTC, merged

2021-09-25 14:22 UTC, VincentLanglet commented
Thanks